export const COUNTRIES = [
    "AFGHANISTAN",
    "AFRIQUE DU SUD",
    "ALBANIE",
    "ALGERIE",
    "ALLEMAGNE",
    "ANDORRE",
    "ANGOLA",
    "ARABIE SAOUDITE",
    "ARGENTINE",
    "ARMENIE",
    "AUSTRALIE",
    "AUTRICHE",
    "AZERBAIDJAN",
    "BAHAMAS",
    "BAHREIN",
    "BANGLADESH",
    "BELARUS",
    "BELGIQUE",
    "BELIZE",
    "BENIN",
    "BHOUTAN",
    "BOLIVIE",
    "BOSNIE HERZEGOVINE",
    "BOTSWANA",
    "BRESIL",
    "BRUNEI DARUSSALAM",
    "BULGARIE",
    "BURKINA FASO",
    "BURUNDI",
    "CAMBODGE",
    "CAMEROUN",
    "CANADA",
    "CAP VERT",
    "CHILI",
    "CHINE",
    "CHYPRE",
    "COLOMBIE",
    "COMORES",
    "CONGO",
    "COREE DU NORD",
    "COREE DU SUD",
    "COSTA RICA",
    "COTE D IVOIRE",
    "CROATIE",
    "CUBA",
    "DANEMARK",
    "DJIBOUTI",
    "DOMINIQUE",
    "EGYPTE",
    "EL SALVADOR",
    "EMIRATS ARABES UNIS",
    "EQUATEUR",
    "ERYTHREE",
    "ESPAGNE",
    "ESTONIE",
    "ETATS UNIS",
    "ETHIOPIE",
    "FIDJI",
    "FINLANDE",
    "FRANCE",
    "GABON",
    "GAMBIE",
    "GEORGIE",
    "GHANA",
    "GIBRALTAR",
    "GRECE",
    "GRENADE",
    "GROENLAND",
    "GUAM",
    "GUATEMALA",
    "GUERNESEY",
    "GUINEE",
    "GUINEE BISSAU",
    "GUINEE EQUATORIALE",
    "GUYANA",
    "HAITI",
    "HONDURAS",
    "HONG KONG",
    "HONGRIE",
    "ILE MAURICE",
    "ILES FEROE",
    "INDE",
    "INDONESIE",
    "IRAN",
    "IRAQ",
    "IRLANDE",
    "ISLANDE",
    "ISRAEL",
    "ITALIE",
    "JAMAIQUE",
    "JAPON",
    "JERSEY",
    "JORDANIE",
    "KAZAKHSTAN",
    "KENYA",
    "KIRGHIZISTAN",
    "KIRIBATI",
    "KOSOVO",
    "KOWEIT",
    "LAOS",
    "LESOTHO",
    "LETTONIE",
    "LIBAN",
    "LIBERIA",
    "LIECHTENSTEIN",
    "LITUANIE",
    "LUXEMBOURG",
    "LYBIE",
    "MACAO",
    "MACEDOINE",
    "MADAGASCAR",
    "MALAISIE",
    "MALI",
    "MALTE",
    "MAROC",
    "MAURITANIE",
    "MEXIQUE",
    "MOLDOVA",
    "MONACO",
    "MONGOLIE",
    "MONTENEGRO",
    "MOZAMBIQUE",
    "MYANMAR",
    "NAMIBIE",
    "NEPAL",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NORVEGE",
    "NOUVELLE ZELANDE",
    "OMAN",
    "OUGANDA",
    "OUZBEKISTAN",
    "PAKISTAN",
    "PALESTINE",
    "PANAMA",
    "PAPOUASIE NOUVELLE GUINEE",
    "PARAGUAY",
    "PAYS BAS",
    "PEROU",
    "PHILIPPINES",
    "POLOGNE",
    "PORTO RICO",
    "PORTUGAL",
    "QATAR",
    "REPUBLIQUE CENTRAFRICAINE",
    "REPUBLIQUE DEMOCRATIQUE DU CONGO",
    "REPUBLIQUE DOMINICAINE",
    "REPUBLIQUE TCHEQUE",
    "ROUMANIE",
    "ROYAUME UNI",
    "RUSSIE",
    "RWANDA",
    "SENEGAL",
    "SERBIE",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINGAPOUR",
    "SLOVAQUIE",
    "SLOVENIE",
    "SOMALIE",
    "SOUDAN",
    "SRI LANKA",
    "SUEDE",
    "SUISSE",
    "SURINAME",
    "SWAZILAND",
    "SYRIE",
    "TADJIKISTAN",
    "TAIWAN",
    "TANZANIE",
    "TCHAD",
    "THAILANDE",
    "TOGO",
    "TONGA",
    "TRINITE ET TOBAGO",
    "TUNISIE",
    "TURKMENISTAN",
    "TURQUIE",
    "UKRAINE",
    "URUGUAY",
    "VANUATU",
    "VATICAN",
    "VENEZUELA",
    "VIETNAM",
    "YEMEN",
    "ZAMBIE",
    "ZIMBABWE"
];


// Fonction de formatage des adresses
export const formatAddress = (address) => {
    if (!address) return address;
    return address.replace(/\s+/g, ' ').trim().toUpperCase();
};

// Fonction de validation du code postal français
export const isValidFrenchPostalCode = (postalCode) => {
    return /^(0[1-9]|[1-8]\d|9[0-8])\d{3}$/.test(postalCode);
};